name: 'US Districts GeoJSON Update'
description: 'Compiles and updates all Congressional districts into GeoJSON'
inputs:
  path:
    description: 'Path to a GeoJSON file to save'
    required: true
    default: ${{ github.workspace }}/districts.geojson"
  districts-repo:
    description: 'Repository that holds the districts'
    required: false
    default: 'unitedstates/districts'
  tag-branch:
    description: 'Branch or git tag value to use'
    required: false
    default: 'gh-pages'
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: arrow-down-circle
  color: purple
