name: 'US Districts GeoJSON Update'
description: 'Compiles and updates all Congressional districts into GeoJSON'
inputs:
  path:
    description: 'Path to a GeoJSON file to save'
    required: true
  zip-link:
    description: 'Link to zip archive of unitedstates/districts'
    required: false
    default: 'https://github.com/unitedstates/districts/archive/gh-pages.zip'
runs:
  using: 'node12'
  main: 'dist/index.js'
