name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Run action
      uses: ./
      id: districts-geojson-update
      with:
        path: districts.geojson

    # test action by showing on different branch
    - name: Show on branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add test GeoJSON from ${{ github.ref }} at ${{ github.sha }}
        branch: checking-if-geojson-worked
        repository: .
        file_pattern: "*.geojson"
        commit_options: '--no-verify --signoff -a'
