name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run action
      uses: ./
      id: districts-geojson-update
      with:
        path: districts.geojson

    - name: Move file and delete old directory
      run: |
        mv ${{ steps.districts-geojson-update.outputs.filePath }} $GITHUB_WORKSPACE

    # test action by showing on different branch
    - name: Show on branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add test GeoJSON from ${{ github.ref }} at ${{ github.sha }}
        branch: checking-if-geojson-worked
        repository: .
        file_pattern: "*.geojson"
